apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-p0f8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-p0f8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-p0f8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-p0f8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-p0f8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ijns-tenant/rhtap-demo-app/hacbs-test-project-p0f8@sha256:d097c00c794d46aaf83d8d8afca33f6c8f3fd7ef0740f1a5377a32e75c24fffe
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
